trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- bash: ls -R $(System.DefaultWorkingDirectory)
- bash: ls -R $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  inputs:
    SourceFolder: '(System.DefaultWorkingDirectory)'
    Contents: |
      **/*.yaml
      **/*.tf
    TargetFolder: '(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'