trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_ssh.pub'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendServiceArm: 'Azure_backend'
    backendAzureRmResourceGroupName: 'storage-rg'
    backendAzureRmStorageAccountName: 'crestora8750304757'
    backendAzureRmContainerName: 'backend-container'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var "ssh_public_key=$(Agent.TempDirectory)/azure_ssh.pub"'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(501f691f-2311-42e3-a356-0c5a1965ebf3)'