trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


variables:
  client_id="1b787950-28d6-4071-b7dd-65669567d1e7"
  client_secret="deU8Q~IYRWWsfuxAqFy5atFmSyWHkZ8Yo1VJdbTl"

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_ssh.pub'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendServiceArm: 'Azure_backend'
    backendAzureRmResourceGroupName: 'storage-rg'
    backendAzureRmStorageAccountName: 'crestora8750304757'
    backendAzureRmContainerName: 'backend-container'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    environmentServiceNameAzureRM: 'Azure_backend'