trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Agent
  jobs:
  - job: ShowAgentDetails
    steps:
    - bash: echo $(Agent.MachineName)
    - bash: echo $(Agent.Name)

- stage: Build
  jobs:
  - job: ShowBuildDetails
    steps:
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.Repository.Id)
    - bash: echo $(Build.Repository.Name)
    - bash: java --version
    - bash: python --version
    - bash: mvn -version
