trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Agent
    jobs:
      - job: ShowAgentDetails
        steps:
          - bash: echo $(Agent.MachineName)
          - bash: echo $(Agent.Name)

  - stage: Build
    jobs:
      - job: ShowBuildDetails
        steps:
          - bash: echo $(Build.BuildId)
          - bash: echo $(Build.BuildNumber)
          - bash: echo $(Build.Repository.Id)
          - bash: echo $(Build.Repository.Name)
          - bash: java --version
          - bash: python --version
          - bash: mvn -version
          - bash: ls -R $(System.DefaultWorkingDirectory)
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*.yml
                **/*.xml
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
