trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker_hub_SC'
        repository: 'crestora/w2_currecncy_exchange'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'